Remove babel-preset-expo to pre-emptively avoid error.
Problem:
 error: bundling failed: Error: Unable to resolve module
 `@expo/vector-icons/MaterialIcons` from `...`:
 Module `@expo/vector-icons/MaterialIcons` does not exist in
 the Haste module map